[package]
name = "evil"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
winapi = { version = "0.3.9", features = [ "winnt", "winbase", "winsvc", "handleapi", "synchapi", "minwindef", "ntdef"] }
lazy_static = "1.4.0"